account/urls.py
from django.urls import path
from . import views


app_name = 'account'
urlpatterns = [
    path('login/', views.login_page, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('register/', views.register_page, name="register"),
    path('<str:pk>', views.profile_page, name="profile_page"),
    path('<str:pk>/problems', views.user_problems_added_page, name="user_problems"),
    path('<str:pk>/solutions', views.user_solutions_added_page, name="user_solutions"),
    path('<str:pk>/comments', views.user_comments_added_page, name="user_comments"),
    path('<str:pk>/notifications', views.user_notifications_page, name="user_notifications"),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name="home"),
]

problembase/urls.py
from django.urls import path, include
from . import views
from .views import ProblemBaseView
app_name = 'problems'
urlpatterns = [
    path('', ProblemBaseView.as_view(template_name="problembase/problemBase.html"), name="problem_base"),
    path('<int:pk>', views.problem_page, name="statement"),
    path('<int:pk>/info', views.problem_page_info, name="info"),
    path('upload', views.upload_problem_page, name="upload_problem"),
    path('<int:pk>/edit', views.problem_edit_page, name="edit_problem"),
    path('watch/<int:pk>', views.watch_problem_page, name="watch_problem"),
    path('history/<int:pk>', views.problem_history_page, name='history'),
    path('upload_api', views.upload_problem_api, name='upload_api'),
    path('problem_statement_api/<int:pk>', views.problem_statement_api, name='problem_statement_api'),
]

problemset/urls.py
from django.urls import path, include
from . import views

app_name = 'problemset'
urlpatterns = [
    path('create/', views.problemset_create_page, name='create'),
    path('edit_basic/<int:pk>/', views.problemset_edit_basic_page, name='edit_basic'),
    path('edit/<int:pk>/', views.problemset_edit_page, name='edit'),
    path('search_problem/', views.ProblemSearchResults.as_view(template_name="problemset/_problemSearchResults.html"), name='search_problem'),
    path('editable_problem_entry/<int:pk>', views.EditableProblemEntry, name='editable_problem_entry'),
    path('save/<int:pk>', views.ProblemsetSave, name='save'),
    path('<int:pk>', views.ProblemsetView, name='problemset'),
    path('problem/<int:problemset_pk>/<int:problem_pk>', views.ProblemInProblemset, name='problem_in_problemset'),
    path('unregister_eiting_notification', views.UnregisterProblemsetEiditingNotification, name='unregister_editing_notification'),
    path('list', views.ProblemsetListView.as_view(template_name="problemset/problemsetList.html"), name="problemset_list"),
]

solutions/urls.py
from django.urls import path, include
from . import views

app_name = 'solutions'
urlpatterns = [
    path('<int:pk>/solutions', views.problem_solution_page, name="solutions"),
    path('<int:pk>/<str:vote>', views.solution_vote_page, name="vote_solution"),
    path('edit/<int:pk>', views.solution_edit_page, name="edit_solution"),
    path('begin_surrender/<int:pk>/<int:as_solved>', views.begin_surrender_page, name="begin_surrender"),
    path('surrender_time/<int:pk>', views.get_surrender_time, name="surrender_time"),
    path('revert_surrender/<int:pk>', views.revert_surrender_page, name="revert_surrender"),
    path('history/<int:pk>', views.solution_history_page, name='history'),
    path('comments', include('comments.urls')),
]

problembase/models.py
from django.db import models
from base.models import Problem, Category
from ckeditor.fields import RichTextField

# Create your models here.
class ProblemHistory(models.Model):
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    problem_statement = RichTextField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    source = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=True)
    comment = models.TextField()

problembase/forms.py
from django.forms import ModelForm
from django import forms
from base.models import Problem, Solution, Comment
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Submit, Row, Column, Div, Field
from .models import ProblemHistory

NAME_PLACEHOLDER = 'MK Problemy rekurencyjne zad 24'
SOURCE_PLACEHOLDER = 'R.L.Graham, D.E.Knuth, O.Patashnik, Matematyka Konkretna, PWN, Warszawa 1996'


class UploadForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column(Field('name', placeholder=NAME_PLACEHOLDER), 'category', css_class="col-lg-4"),
            Field('source', placeholder=SOURCE_PLACEHOLDER),
            'problem_statement',
            Div(Submit('submit', 'Zapisz', css_class='d-flex'), css_class='d-flex flex-row justify-content-end'),
        )
        self.fields["problem_statement"].label = ""
        self.fields["name"].label = "Nazwa zadania"
        self.fields["category"].label = "Kategoria"
        self.fields["source"].label = "Źródło"


    class Meta:
        model = Problem
        fields = ['name', 'category', 'source', 'problem_statement']



class EditProblemForm(ModelForm):
    comment = forms.CharField(widget=forms.Textarea)
    problem_instance = None
    old = {}
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.problem_instance = kwargs['instance']
        self.old = {
            'name': self.problem_instance.name,
            'category': self.problem_instance.category,
            'source': self.problem_instance.source,
            'problem_statement': self.problem_instance.problem_statement
        }
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column(Field('name', placeholder=NAME_PLACEHOLDER), 'category', css_class="col-lg-4"),
            Field('source', placeholder=SOURCE_PLACEHOLDER),
            'problem_statement',
            Field('comment', rows=2),
            Div(Submit('submit', 'Zapisz', css_class='d-flex'), css_class='d-flex flex-row justify-content-end'),
        )
        self.fields["problem_statement"].label = ""
        self.fields["name"].label = "Nazwa zadania"
        self.fields["category"].label = "Kategoria"
        self.fields["source"].label = "Źródło"
        self.fields["comment"].label = "Co zostało zmienione w zadaniu?"

    class Meta:
        model = Problem
        fields = ['name', 'category', 'source', 'problem_statement', 'comment']

    def save(self, **kwargs):
        if not ProblemHistory.objects.filter(problem=self.problem_instance).exists():
            ProblemHistory.objects.create(
                problem=self.problem_instance,
                name=self.old['name'],
                source=self.old['source'],
                problem_statement=self.old['problem_statement'],
                category=self.old['category'],
            )
        ProblemHistory.objects.create(
            problem=self.problem_instance,
            name=self.cleaned_data['name'],
            source=self.cleaned_data['source'],
            problem_statement=self.cleaned_data['problem_statement'],
            category=self.cleaned_data['category'],
            comment=self.cleaned_data['comment'],
        )
        instance = super().save(commit=False)
        instance.edited = True
        instance.save()
        return instance

problembase/views.py
import json
from datetime import timedelta
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.db.models import Sum
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic.list import ListView
from django.http import JsonResponse

from base.models import Problem, Category, Solution, SolutionVote, Comment, CommentVote
from base.models import UserToProblem
from comments.utils import update_comment_upvote_counter
from notifications.utils import notify_new_comment, notify_new_solution, notify_new_problem
from notifications.views import show_notifications
from problembase.utils import has_user_solved_problem, get_problem_stats, add_stats_to_problems, add_status_to_problems, \
    get_watchers_of_problem
from ranking.utils import notify_problem_solved
from solutions.forms import SolutionForm
from solutions.utils import update_solution_upvote_counter, get_waiting_for_surrender_status
from .forms import UploadForm, EditProblemForm
from .models import ProblemHistory
from problemset.models import Problemset
from problemset.utils import problem_in_problemset_preview, get_basic_problemset_data_for_problem


@method_decorator(show_notifications, name='dispatch')
class ProblemBaseView(ListView):
    model = Problem
    paginate_by = 15

    def get_queryset(self):
        q = self.request.GET.get('q') if self.request.GET.get('q') is not None else ''
        object_list = Problem.objects.filter(
            Q(category__name__icontains=q) |
            Q(name__icontains=q)
        ).order_by('-creation_date')
        return object_list

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        add_stats_to_problems(data['object_list'])
        add_status_to_problems(data['object_list'], self.request.user)
        return data


@show_notifications
@login_required(login_url='account:login')
def problem_page(request, pk):
    problem = get_object_or_404(Problem, pk=pk)
    utp, _ = UserToProblem.objects.get_or_create(problem=problem, user=request.user)
    utp.timestamp()

    solution_form = SolutionForm()

    if request.method == 'POST':
        solution_form = SolutionForm(request.POST)

        if solution_form.is_valid():
            solution = solution_form.save(commit=False)

            setattr(solution, 'user', request.user)
            setattr(solution, 'problem', problem)

            solution.save()
            notify_new_solution(solution)
            notify_problem_solved(problem, request.user)

            return redirect('solutions:solutions', pk=problem.id)

    problem_stats = get_problem_stats(problem)

    context = {
        'name': problem.name,
        'problem_statement': problem.problem_statement,
        'pk': pk,
        'solution_form': solution_form,
        'watching_count': problem_stats['watching'],
        'solved_count': problem_stats['solved'],
        'watched': utp.is_watching,
        'added_by': problem.added_by,
        'edited': problem.edited,
        'surrendered': utp.surrendered,
        'waiting_for_surrender': get_waiting_for_surrender_status(utp),
        'surrendered_as_solved': utp.surrendering_as_solved,
        'sent_solution': Solution.objects.filter(problem=problem, user=request.user).exists(),
    }
    if utp.seen_in_problemset:
        context['problemset_data'] = problem_in_problemset_preview(problem, utp.seen_in_problemset, request.user)
        print(context['problemset_data'])

    return TemplateResponse(request, "problembase/problemStatement.html", context)


@show_notifications
@login_required(login_url='account:login')
def problem_page_info(request, pk):
    problem = get_object_or_404(Problem, pk=pk)

    problem_stats = get_problem_stats(problem)
    context = {
        'name': problem.name,
        'pk': pk,
        'problem_statement': problem.problem_statement,
        'added_by': problem.added_by,
        'creation_date': problem.creation_date,
        'category': problem.category,
        'source': problem.source,
        'edited': problem.edited,
        'solved_count': problem_stats['solved'],
        'problemset_data': get_basic_problemset_data_for_problem(problem, request.user),
    }

    return TemplateResponse(request, "problembase/problemInfo.html", context);


@show_notifications
@login_required(login_url='account:login')
def upload_problem_page(request):
    upload_form = UploadForm()

    if request.method == 'POST':
        upload_form = UploadForm(request.POST)

        if upload_form.is_valid():
            created_problem = upload_form.save(commit=False)

            setattr(created_problem, "added_by", request.user)
            setattr(created_problem, "watchers", {created_problem.name: 1})
            setattr(created_problem, "solved", {created_problem.name: 0})

            created_problem.save()

            # Tutaj dodajemy userToProblem, automatycznie obserwujemy dodany problem.
            utp = UserToProblem()
            setattr(utp, 'user', request.user)
            setattr(utp, 'problem', created_problem)
            setattr(utp, 'is_watching', True)
            utp.timestamp()
            utp.save()

            #notify_new_problem(created_problem)

            return redirect('problems:problem_base')

    context = {'upload_form': upload_form}

    return TemplateResponse(request, "problembase/problemUpload.html", context)


@login_required(login_url='account:login')
def watch_problem_page(request, pk):
    problem = get_object_or_404(Problem, pk=pk)
    utp, _ = UserToProblem.objects.get_or_create(problem=problem, user=request.user)

    if utp.is_watching:
        setattr(utp, 'is_watching', False)
    else:
        setattr(utp, 'is_watching', True)

    utp.save()

    return HttpResponseRedirect(reverse('problems:statement', kwargs={'pk': pk}))


@show_notifications
@login_required(login_url='account:login')
def problem_edit_page(request, pk):
    problem = get_object_or_404(Problem, pk=pk)

    if request.user != problem.added_by:
        return redirect('problems:statement', pk=problem.id)

    problem_form = EditProblemForm(request.POST or None, instance=problem)
    if problem_form.is_valid():
        problem = problem_form.save(commit=False)

        problem.save()
        return redirect('problems:statement', pk=problem.id)

    context = {
        'problem_form': problem_form,
        'name': problem.name,
        'problem_id': pk,
        'pk': problem.id,
        'problem_statement': problem.problem_statement,
    }
    return TemplateResponse(request, "problembase/problemEdit.html", context)

def problem_history_page(request, pk):
    problem = get_object_or_404(Problem, pk=pk)

    history_list = ProblemHistory.objects.filter(problem=problem).order_by('-date')
    context = {
        'problem_name': problem.name,
        'pk': pk,
        'history_list': history_list,
    }

    return render(request, "problembase/_problemHistory.html", context)

@login_required(login_url='account:login')
def upload_problem_api(request):
    upload_form = UploadForm()

    if request.method == 'POST':
        upload_form = UploadForm(request.POST)
        response_data = {}
        if upload_form.is_valid():
            created_problem = upload_form.save(commit=False)

            setattr(created_problem, "added_by", request.user)
            created_problem.save()

            utp = UserToProblem()
            setattr(utp, 'user', request.user)
            setattr(utp, 'problem', created_problem)
            setattr(utp, 'is_watching', True)
            utp.timestamp()
            utp.save()

            response_data = {
                'result': 'Success',
                'problem_id': created_problem.id,
            }
        else:
            response_data = {
                'result': 'Form invalid',
            }
        return JsonResponse(response_data)
    else:
        raise PermissionDenied()

def problem_statement_api(request, pk):
    problem = get_object_or_404(Problem, pk=pk)
    return render(request, 'problembase/_problemStatementApi.html', {'statement': problem.problem_statement})

problembase/templates/problembase/_pagination_nav.html
{% if page_obj.paginator.num_pages != 1 %}
<div class="pagination h5">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}{% for item in request.GET.items %}{% if item.0 != 'page' %}&{{ item.0 }}={{ item.1 }}{% endif %}{% endfor %}"><i class="bi bi-arrow-left-square"></i></a>
        {% else %}
            <i class="invisible bi bi-arrow-left-square"></i>
        {% endif %}

        <span class="current px-1">
            {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}{% for item in request.GET.items %}{% if item.0 != 'page' %}&{{ item.0 }}={{ item.1 }}{% endif %}{% endfor %}"><i class="bi bi-arrow-right-square"></i></a>
        {% else %}
            <i class="invisible bi bi-arrow-right-square"></i>
        {% endif %}
    </span>
</div>
{% endif %}

problembase/templates/problembase/_problemHistory.html
<div class="d-flex flex-column">
    {% for entry in history_list %}
        <div class="d-flex flex-column border-bottom p-2">
            <p class="text-secondary">{{ entry.date }}</p>
            <p>Nazwa: {{ entry.name }}</p>
            {{ entry.problem_statement|safe }}
            <p>Kategoria: {{ entry.category }}</p>
            <p>Zródło: {{ entry.source|urlize }}</p>
            <div class="d-flex flex-row justify-content-end">
                {%  if entry.comment %} <p class="text-secondary">{{ entry.comment }}</p> {% endif %}
            </div>
        </div>
    {% endfor %}
</div>

problembase/templates/problembase/_problemStatementApi.html
<p>{{  statement|safe }}</p>

problembase/templates/problembase/_problemStatus.html
{% if problem.status %}
    {% if problem.status == 'solved' %}
        <span class="text-warning" title="Rozwiązałeś to zadanie"><b>R</b></span>
    {% elif problem.status == 'surrendered' %}
        <span class="text-secondary" title="Poddałeś to zadanie"><b>P</b></span>
    {% endif %}
{% endif %}

problembase/templates/problembase/commentSection.html
<div class="d-flex flex-column lh-sm w-100" style="font-size: 14px;">
    {% for comment in comments %}
        <div class="d-flex d-row border-top border-2 pt-2" mb-0>
            <a class="text-decoration-none" href="{% url 'account:profile_page' comment.user.id %}">@{{ comment.user.username }}</a>
            &nbsp;
            <p class="text-secondary mb-1">{{ comment.creation_date }}</p>
            {% if comment.user == request.user %}
                &nbsp;
                <a href="{% url 'solutions:comments:delete' pk=comment.id %}" class="link-secondary"
                   onclick="return confirm('Czy na pewno chcesz usunąć komentarz?');">usuń</a>
            {% endif %}
        </div>
        <div class="d-flex d-row mt-0 text-break">
            <p class="mb-1">{{ comment.content }}</p>
        </div>
        <div class="d-flex d-row justify-content-end align-items-center">
            <a href="{% url 'solutions:comments:vote' pk=comment.id vote='upvote' %}" class="link-dark p-1">
                <i class="bi bi-caret-up{% if comment.upvoted %}-fill{% endif %}"></i>
            </a>
            <p class="m-2 prevent-select">{{ comment.upvote_counter }}</p>
            <a href="{% url 'solutions:comments:vote' pk=comment.id vote='downvote' %}"  class="text-dark p-1">
                <i class="bi bi-caret-down{% if comment.downvoted %}-fill{% endif %}"></i>
            </a>
            <div class="px-3"></div>
        </div>
    {% endfor %}
    <div class="d-flex flex-row justify-content-end">
        <input type="hidden" name="solution_id" value="{{ solution_id }}">
        <a class="pl-3 mb-4 text-decoration-none link-primary add-comment" style="cursor: pointer;">Dodaj komentarz</a>
    </div>
</div>

problembase/templates/problembase/problem.html
{% extends "base/base.html" %}
{% block title %} {{ name }} {% endblock %}

{% block content %}
    <div class="container center-block flex-column mt-4" style="width: {% if problemset_data and problemset_data.rows %}75% {% else %}60%{% endif %};">
    <nav class="px-4 align-items-center navbar navbar-expand-lg navbar-light bg-light mb-3">
        <div class="navbar-nav w-100">
            <h1 class="m-auto navbar-brand ">Zadanie</h1>
            <div style="width: 15px;"></div>
            <a class="ml-4 nav-item nav-link {% if request.resolver_match.view_name == 'problems:statement' %}active{% endif %}" href="{% url 'problems:statement' pk=pk %}">Treść</a>
            <a class="ml-4 nav-item nav-link {% if request.resolver_match.view_name == 'solutions:solutions' %}active{% endif %}" href="{% url 'solutions:solutions' pk=pk %}">Rozwiązania &nbsp;{{ solved_count }}</a>
            <a class="ml-4 nav-item nav-link {% if request.resolver_match.view_name == 'problems:info' %}active{% endif %}" href="{% url 'problems:info' pk=pk %}">Info</a>
            <div class='d-flex flex-fill justify-content-end align-self-center'>
                {% if problemset_data %}
                <a class='my-0 py-0 text-decoration-none text-secondary' href="{% url 'problemset:problemset' pk=problemset_data.id %}">Powrót do zbiorku <i class="bi bi-arrow-return-left"></i></a>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="d-flex flex-row w-100">
        <div class="flex-column justify-content-center mx-4 py-2 {% if problemset_data and problemset_data.rows %} w-75 {% else %} w-100 {% endif %}">
            {% block innerContent %}
            {% endblock %}
        </div>
        <div class="ms-4">
            {% if problemset_data and problemset_data.rows %}
                {% include 'problemset/_problemsetPreview.html' with problemset_data=problemset_data%}
            {% endif %}
        </div>
    </div>
    </div>
{% endblock %}

problembase/templates/problembase/problemBase.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
    <div class="home-container d-flex flex-row p-4 h-100">
        <nav class="collapse d-lg-block sidebar collapse">
          <div class="list-group list-group-flush mx-3 mt-4">
            <h3 class="pl-2">Kategoria</h3>

            <a style="text-decoration: none;"
               href="{% url 'problems:problem_base' %}"
                class="list-group-item list-group-item-action py-2 ripple">
                <span> Wszystkie kategorie </span>
            </a>
            {% for category in categories %}
                <a style="text-decoration: none;"
                   href="{% url 'problems:problem_base' %}?q={{ category }}"
                   class="list-group-item list-group-item-action py-2 ripple">
                    <span> {{ category }} </span>
                </a>
            {% endfor %}
            <div class="list-group-item mt-4">
                <a class="btn btn-outline-secondary" href="{% url 'problems:upload_problem' %}">Dodaj zadanie</a>
            </div>
          </div>
        </nav>

        <div class="d-flex" style="width: 120px"><!-- spacing between categories and problems --></div>

        <div class="d-flex flex-column mt-5">
            <table class="table table-borderless table-hover">
            <tbody>
                {% for problem in object_list %}
                    {% include 'problembase/problemDBEntry.html' with problem=problem %}
                {% endfor %}
            </tbody>
            </table>
            <div class="d-flex flex-row justify-content-center">
                {% include 'problembase/_pagination_nav.html' with page_obj=page_obj %}
            </div>
        </div>
    </div>
{% endblock %}

problembase/templates/problembase/problemDBEntry.html
<tr class="h5 mb-0 align-middle problem-db-entry" data-problem-id="{{ problem.id }}">
    <td>
        {{ problem.category }}
    </td>
    <td>
        <a class="problem-link d-inline" href="{% url 'problems:statement' problem.id  %}" data-problem-id="{{ problem.id }}">{{ problem.name }}</a>
        {% include 'problembase/_problemStatus.html' with problem=problem %}
    </td>
    <td style="width: 160px;"></td>
    <td class="prevent-select" title="Rozwiązania">{{ problem.solved }}</td>
    <td class="prevent-select" title="Rozwiązania"><i class="bi bi-check"></i></td>
    <td></td>
    <td class="prevent-select" title="Obserwujący">{{ problem.watchers_count }}</td>
    <td class="prevent-select" title="Obserwujący"><i class="bi bi-eye mx-0 p-0"></i></td>
</tr>

problembase/templates/problembase/problemEdit.html
{% extends "problembase/problem.html" %}

{% load crispy_forms_tags %}

{% block innerContent %}
<!--    <h1 class="mb-3">Edytujesz zadanie "{{ name }}"</h1>-->
    {% crispy problem_form %}

{% endblock %}

problembase/templates/problembase/problemInfo.html
{% extends "problembase/problem.html" %}
{% load static %}

{% block innerContent %}
    <p>Nazwa zadania: {{ name }}</p>
    <p>Kategoria: {{ category }}</p>
    <p>Źródło: {{ source|urlize }}</p>
    <p>Dodane przez <a href="{% url 'account:profile_page' added_by.id %}">@{{ added_by.username }}</a> w dniu {{ creation_date }}</p>
    {% if edited %}
        <p>
            <a class="link-secondary problem-history-link"
               href="{% url 'problems:history'  pk=pk %}">Historia zmian</a>
        </p>
    {% endif %}
    <!--
    <a href="#" class="btn btn-danger">Zgłoś</a>
    -->
    {% include 'problembase/_problemHistoryModal.html' %}
{% endblock %}
{% block scripts %}
    <script src="{% static 'problembase/problem_history.js' %}"></script>
{% endblock %}

problembase/templates/problembase/problemStatement.html
{% extends "problembase/problem.html" %}
{% load custom_tags %}
{% load crispy_forms_tags %}
{% load static %}

{% block innerContent %}
<div class="justify-content-center d-flex flex-column" style="padding-bottom: 200px;">
    <div class="d-flex flex-row w-100">
        <div class="d-flex flex-fill">
            <h3>{{ name }}</h3>
        </div>
        <div class="d-flex flex-row justify-content-end flex-fill">

            {% if added_by == request.user %}
                <div class="d-flex flex-column justify-content-center h-100 px-3 align-self-end">
                    <a class="link-secondary"
                       href="{% url 'problems:edit_problem'  pk=pk %}">Edytuj</a>
                </div>
            {% endif %}
            {% if edited %}
                <div class="d-flex flex-column justify-content-center h-100 px-3 align-self-end">
                    <a class="link-secondary problem-history-link"
                       href="{% url 'problems:history'  pk=pk %}">Historia zmian</a>
                </div>
            {% endif %}

            <div class="d-flex flex-column h-100 justify-content-center align-items-center">
                <div class="d-flex flex-row align-self-end">
                    <div class="d-flex mr-2">
                        <i class="bi bi-eye mx-2 p-0"></i>
                    </div>
                    <div class="d-flex">
                        {{ watching_count }}
                    </div>
                </div>
            </div>

            <div class="d-flex flex-column justify-content-center h-100 px-3 align-self-end">
                <a class="btn align-self-end {% if watched %} btn-secondary {% else %} btn-outline-secondary {% endif %}"
                   href="{% url 'problems:watch_problem' pk=pk %}">Śledź</a>
            </div>

        </div>
    </div>


    <div class="d-flex flex-row p-0 m-0 w-100">
        <div class="d-flex flex-column w-100">
        <div class="flex-column justify-content-center text-break fs-5 py-4 problem-statement">
            <p>{{ problem_statement|safe }}</p>
        </div>
        <div class="ml-4">
            {% if sent_solution %}
                <h5>Wysłałeś już rozwiązanie do tego zadania!</h5>
            {% else %}
                {% if waiting_for_surrender %}
                    {% include 'solutions/_surrenderTimer.html' with pk=pk surrendered_as_solved=surrendered_as_solved%}
                {% else %}
                <div class="d-flex flex-row justify-content-center w-100 mt-5 align-middle">
                    {% if not surrendered %}
                    <button class="btn btn-outline-danger mb-4 mx-3" role="button" id='surrender-btn'>
                        Poddaję się
                    </button>
                    {% endif %}
                    <button class="btn btn-outline-secondary mb-4 mx-3" data-bs-toggle="collapse" href="#solutionForm"
                            role="button"
                            aria-expanded="false" aria-controls="solutionForm" data-bs-target="#solutionForm">
                        Dodaj rozwiązanie
                    </button>
                    {% if not surrendered %}
                    <button class="btn btn-outline-success mb-4 mx-3" role="button" id='surrender-as-solved-btn'>
                        Oznacz jako zrobione
                    </button>
                    {% endif %}
                </div>
                <div class="mt-2">
                    {% include 'solutions/addingSolutionInfo.html' with surrendered=surrendered %}
                </div>
                <div class="collapse" id="solutionForm">
                    {% crispy solution_form %}
                </div>
                {% endif %}
            {% endif %}
        </div> </div>
    </div>
</div>
{% include 'problembase/_problemHistoryModal.html' %}
{% endblock %}

{% block scripts %}
    <script src="{% static 'problembase/problem_history.js' %}"></script>
    <script>
        var surrender_begin_url = "{% url 'solutions:begin_surrender' pk=pk as_solved=0 %}?version=1";
        var surrender_as_solved_begin_url = "{% url 'solutions:begin_surrender' pk=pk as_solved=1 %}?version=1";
        var surrender_timer_url = "{% url 'solutions:surrender_time' pk=pk %}";
    </script>
    <script src="{% static 'solutions/surrender.js' %}"></script>
    {% if waiting_for_surrender %}
    <script>
        show_timer();
    </script>
    {% endif %}
{% endblock %}

problembase/templates/problembase/problemUpload.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="flex-column p-4">
        <h2>Dodaj zadanie</h2>
        {% crispy upload_form %}
    </div>
{% endblock %}