account/urls.py
from django.urls import path
from . import views


app_name = 'account'
urlpatterns = [
    path('login/', views.login_page, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('register/', views.register_page, name="register"),
    path('<str:pk>', views.profile_page, name="profile_page"),
    path('<str:pk>/problems', views.user_problems_added_page, name="user_problems"),
    path('<str:pk>/solutions', views.user_solutions_added_page, name="user_solutions"),
    path('<str:pk>/comments', views.user_comments_added_page, name="user_comments"),
    path('<str:pk>/notifications', views.user_notifications_page, name="user_notifications"),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name="home"),
]

solutions/urls.py
from django.urls import path, include
from . import views

app_name = 'solutions'
urlpatterns = [
    path('<int:pk>/solutions', views.problem_solution_page, name="solutions"),
    path('<int:pk>/<str:vote>', views.solution_vote_page, name="vote_solution"),
    path('edit/<int:pk>', views.solution_edit_page, name="edit_solution"),
    path('begin_surrender/<int:pk>/<int:as_solved>', views.begin_surrender_page, name="begin_surrender"),
    path('surrender_time/<int:pk>', views.get_surrender_time, name="surrender_time"),
    path('revert_surrender/<int:pk>', views.revert_surrender_page, name="revert_surrender"),
    path('history/<int:pk>', views.solution_history_page, name='history'),
    path('comments', include('comments.urls')),
]

solutions/models.py
from ckeditor.fields import RichTextField
from django.db import models

from base.models import Solution


class SolutionHistory(models.Model):
    solution = models.ForeignKey(Solution, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    content = RichTextField(blank=True, null=True)
    comment = models.TextField(null=True)

solutions/forms.py
from django.forms import ModelForm
from django import forms
from base.models import Problem, Solution, Comment
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Submit, Row, Column, Div, Field
from .models import SolutionHistory

class SolutionForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(Column('content', css_class='form-group col-md-8 mb-0'), css_class='form-row'),
            Column(Div(Submit('submit', 'Zapisz', css_class='px-4'), css_class='justify-content-end d-flex flex-row px-4'), css_class='form-group col-md-8 mb-0')
        )
        self.fields["content"].label = ""

    class Meta:
        model = Solution
        fields = ['content']

class EditSolutionForm(ModelForm):
    comment = forms.CharField(widget=forms.Textarea())
    solution_instance = None
    old_content = ''
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.solution_instance = kwargs['instance']
        self.old_content = self.solution_instance.content
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(Column('content', Field('comment', rows=2), css_class='form-group col-md-8 mb-0'), css_class='form-row'),
            Column(Div(Submit('submit', 'Zapisz', css_class='px-4'), css_class='justify-content-end d-flex flex-row px-4'), css_class='form-group col-md-8 mb-0')
        )
        self.fields["content"].label = ""
        self.fields["comment"].label = "Co zmieniło się w rozwiązaniu?"

    class Meta:
        model = Solution
        fields = ['content', 'comment']

    def save(self, **kwargs):
        if not SolutionHistory.objects.filter(solution=self.solution_instance).exists():
            SolutionHistory.objects.create(
                solution=self.solution_instance,
                content=self.old_content,
            )
        SolutionHistory.objects.create(
            solution=self.solution_instance,
            content=self.cleaned_data['content'],
            comment=self.cleaned_data['comment']
        )
        instance = super().save(commit=False)
        instance.edited = True
        instance.save()
        return instance

solutions/views.py
import json
from datetime import timedelta
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.db.models import Sum
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic.list import ListView

from base.models import Problem, Category, Solution, SolutionVote, Comment, CommentVote
from base.models import UserToProblem
from comments.forms import CommentForm
from notifications.utils import notify_new_comment, notify_new_solution, notify_new_problem
from notifications.views import show_notifications
from problembase.utils import has_user_solved_problem, get_problem_stats, add_stats_to_problems, add_status_to_problems, \
    get_watchers_of_problem
from problemset.utils import get_basic_problemset_data_for_problem
from ranking.utils import notify_problem_solved
from solutions.utils import update_solution_upvote_counter
from .forms import EditSolutionForm, SolutionForm
from .models import SolutionHistory
from .utils import can_see_solutions, get_waiting_for_surrender_status


# Create your views here.
@show_notifications
@login_required(login_url='account:login')
def problem_solution_page(request, pk):
    problem = get_object_or_404(Problem, pk=pk)
    solutions = Solution.objects.filter(problem=problem).order_by('-upvote_counter')

    comment_form = CommentForm()

    for solution in solutions:
        setattr(solution, 'upvoted', SolutionVote.objects.filter(user=request.user, solution=solution, value=1).exists())
        setattr(solution, 'downvoted', SolutionVote.objects.filter(user=request.user, solution=solution, value=-1).exists())
        setattr(solution, 'comments', Comment.objects.filter(solution=solution).order_by('creation_date'))
        for comment in solution.comments:
            setattr(comment, 'upvoted', CommentVote.objects.filter(user=request.user, comment=comment, value=1).exists())
            setattr(comment, 'downvoted', CommentVote.objects.filter(user=request.user, comment=comment, value=-1).exists())

    utp, _ = UserToProblem.objects.get_or_create(problem=problem, user=request.user)

    display_solutions = can_see_solutions(request.user, problem)
    problem_stats = get_problem_stats(problem)
    context = {
        'name': problem.name,
        'pk': pk,
        'problem_statement': problem.problem_statement,
        'solutions': solutions,
        'comment_form': comment_form,
        'display_solutions': display_solutions,
        'waiting_for_surrender': get_waiting_for_surrender_status(utp),
        'surrendered_as_solved': utp.surrendering_as_solved,
        'solved_count': problem_stats['solved'],
        'problemset_data': get_basic_problemset_data_for_problem(problem, request.user),
    }

    return TemplateResponse(request, "solutions/problemSolution.html", context)

@login_required(login_url='account:login')
def solution_vote_page(request, pk, vote):
    solution = get_object_or_404(Solution, pk=pk)
    if vote == 'upvote':
        if request.user != solution.user:
            vote, _ = SolutionVote.objects.get_or_create(solution=solution, user=request.user)
            if vote.value == 1:
                vote.value = 0
            else:
                vote.value = 1
            vote.save()
            update_solution_upvote_counter(solution)

    elif vote == 'downvote':
        if request.user != solution.user:
            vote, _ = SolutionVote.objects.get_or_create(solution=solution, user=request.user)
            if vote.value == -1:
                vote.value = 0
            else:
                vote.value = -1
            vote.save()
            update_solution_upvote_counter(solution)

    return JsonResponse({'count': solution.upvote_counter})

@show_notifications
@login_required(login_url='account:login')
def solution_edit_page(request, pk):
    solution = get_object_or_404(Solution, pk=pk)
    problem = solution.problem

    if request.user != solution.user:
        return redirect('solutions:solutions', pk=problem.id)

    solution_form = EditSolutionForm(request.POST or None, instance=solution)

    if solution_form.is_valid():
        solution = solution_form.save(commit=False)

        solution.save()
        return redirect('solutions:solutions', pk=problem.id)

    context = {
        'solution_form': solution_form,
        'name': problem.name,
        'solution_id': pk,
        'pk': problem.id,
        'problem_statement': problem.problem_statement,
    }

    return TemplateResponse(request, "solutions/solutionEdit.html", context)

@login_required(login_url='account:login')
def begin_surrender_page(request, pk, as_solved):
    problem = get_object_or_404(Problem, pk=pk)
    utp, _ = UserToProblem.objects.get_or_create(user=request.user, problem=problem)

    utp.surrendering_as_solved = (as_solved == 1)
    utp.start_surrendering()

    response_data = {}
    response_data['result'] = 'success!'
    return HttpResponse(
        json.dumps(response_data),
        content_type="application/json"
    )


@login_required(login_url='account:login')
def get_surrender_time(request, pk):
    problem = get_object_or_404(Problem, pk=pk)
    utp, _ = UserToProblem.objects.get_or_create(user=request.user, problem=problem)

    if utp.began_surrendering == False:
        raise PermissionDenied()
    end_time = utp.surrender_end_time
    # Calculate the remaining time (time left until end_time)
    remaining_time = end_time - timezone.now()

    # Extract minutes and seconds from the remaining time
    minutes = remaining_time.seconds // 60
    seconds = remaining_time.seconds % 60

    response_data = {}
    response_data['result'] = 'success'
    response_data['remaining_minutes'] = minutes
    response_data['remaining_seconds'] = seconds

    return HttpResponse(
        json.dumps(response_data),
        content_type="application/json"
    )


@login_required(login_url='account:login')
def revert_surrender_page(request, pk):
    problem = get_object_or_404(Problem, pk=pk)
    utp, _ = UserToProblem.objects.get_or_create(problem=problem, user=request.user)

    if not utp.surrendered:
        utp.began_surrendering = False
        utp.surrender_end_time = None
        utp.save()

    return redirect('solutions:solutions', pk=problem.id)

@login_required(login_url='account:login')
def solution_history_page(request, pk):
    solution = get_object_or_404(Solution, pk=pk)
    problem = solution.problem
    utp, _ = UserToProblem.objects.get_or_create(problem=problem, user=request.user)

    if not (has_user_solved_problem(request.user, problem) or utp.surrendered):
        raise PermissionDenied()

    history_list = SolutionHistory.objects.filter(solution=solution).order_by('-date')
    context = {
        'problem_name': problem.name,
        'pk': pk,
        'history_list': history_list,
    }

    return render(request, "solutions/_solutionHistory.html", context)

solutions/templates/solutions/_solutionHistory.html
<div class="d-flex flex-column">
    {% for entry in history_list %}
        <div class="d-flex flex-column border-bottom p-2">
            <p class="text-secondary">{{ entry.date }}</p>
            {{ entry.content|safe }}
            <div class="d-flex flex-row justify-content-end">
                {%  if entry.comment %} <p class="text-secondary">{{ entry.comment }}</p> {% endif %}
            </div>
        </div>
    {% endfor %}
</div>

solutions/templates/solutions/_surrenderTimer.html
{% if surrendered_as_solved %}
    <h4>Oznaczyłeś zadanie jako rozwiązane</h4>
    <p>gdy upłynie czas zobaczysz rozwiązania</p>
    <div class='d-flex flex-row justify-content-center h1 text-success'><span id='timer'>
            <div class='spinner-border spinner-border-lg' id='counter-spinner'></div>
        </span></div>
    <div class="d-flex flex-row justify-content-end mx-5">
        <a class='btn btn-primary' href="{% url 'solutions:revert_surrender' pk=pk %}">Anuluj rozwiązanie</a>
    </div>
{% else %}
<h4>Poddałeś się</h4>
<p>gdy upłynie czas zobaczysz rozwiązania</p>
<div class='d-flex flex-row justify-content-center h1 text-danger'><span id='timer'>
            <div class='spinner-border spinner-border-lg' id='counter-spinner'></div>
        </span></div>
<div class="d-flex flex-row justify-content-end mx-5">
    <a class='btn btn-primary' href="{% url 'solutions:revert_surrender' pk=pk %}">Anuluj poddanie się</a>
</div>
{% endif %}

solutions/templates/solutions/addingSolutionInfo.html
<p>
{% if surrendered == False %}
    Aby zobaczyć rozwiązania wybierz jedną z opcji.
{% else %}
    Nadal możesz wysłać swoje rozwiązanie :)&nbsp;
{% endif %}
    <a class="text-decoration-none" href="#" data-bs-toggle="modal" data-bs-target="#solutionInfoModal">Więcej informacji</a>
</p>

<!-- Modal -->
<div class="modal fade" id="solutionInfoModal" tabindex="-1" aria-labelledby="solutionInfoModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="solutionInfoModalLabel">Wysyłanie rozwiązań</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <p>Jeśli wyślesz swoje rozwiązanie będziesz mógł od razu zobaczyć rozwiązania innych.</p>
          <p>Wybierając poddanie się lub oznaczenie jako rozwiązane dostęp do rozwiązań otrzymasz po 10 minutach.</p>
          <p>Zadania do których wyślesz rozwiązania lub oznaczysz jako rozwiązane będą oznaczane złotą literką R, te przy których się poddasz oznaczone są literą P.
          Dzięki temu będziesz mógł szybko zajrzeć do zadań z którymi miałeś problem, jak i cieszyć się z tych które rozwiązałeś.</p>
          <p>Wysyłanie rozwiązań umożliwia dostanie informacji zwrotnej od innych ludzi, coś dzięki czemu najszybciej się rozwijamy ;)</p>
          <p>Proszę nie wysyłaj rozwiązań w stylu "sdlkjglhjbf". Jeżeli nie rozwiązałeś zadania po prostu użyj funkcji "poddaję się".</p>
      </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Ok</button>
      </div>
    </div>
  </div>
</div>

solutions/templates/solutions/problemSolution.html
{% extends "problembase/problem.html" %}

{% load crispy_forms_tags %}
{% load static %}
{% static 'static_jquery/js/jquery.js' %}

{% block innerContent %}
    <div class="justify-content-center d-flex flex-column" style="padding-bottom: 200px;">
        <div class="d-flex">
            <h1>{{ name }}</h1>
        </div>

        {% if not display_solutions %}
            {% include 'solutions/problemSurrender.html' %}
        {% else %}

        <div>
            <div id='problem-statement' class="overflow-hidden" style="max-height: 9lh; ">
                {{ problem_statement|safe }}
            </div>
            {% for solution in solutions %}

                <hr>
                <div class="home-container d-flex flex-row w-100">
                    <div class="d-flex flex-column">
                        <div class="d-flex mt-1">
                            <a class="text-decoration-none" href="{% url 'account:profile_page' solution.user.id %}">@{{ solution.user.username }}</a>
                        </div>

                        <div class="d-flex text-secondary">
                            {{ solution.creation_date }}
                        </div>
                        {% if solution.user == user %}
                            <div class="d-flex">
                                <a class="link-secondary"
                                   href="{% url 'solutions:edit_solution'  pk=solution %}">Edytuj</a>
                            </div>
                        {% endif %}
                        {% if solution.edited %}
                            <div class="d-flex text-secondary">
                                <a class="link-secondary solution-history-link"
                                   href="{% url 'solutions:history' pk=solution %}">Historia zmian</a>
                            </div>
                        {% endif %}

                    </div>
                    <div class="px-4 d-flex"><!-- spacing between solution info and solution content --></div>
                    <div class="d-flex flex-column mt-0 w-100" style="word-wrap: break-word; min-width: 0;">
                        <p class="mb-4">{{ solution.content|safe }}</p>
                        <div class="d-flex flex-row mb-3 mt-4 justify-content-end">
                            <div class="d-flex flex-column align-items-center justify-content-center h-100 px-2 h3">
                                {{ solution.upvote_counter }}
                            </div>
                            <div class="d-flex flex-row px-1 ml-2 me-3">
                                <a class="vote-solution btn align-self-end {% if solution.upvoted %} btn-success {% else %} btn-outline-success {% endif %}
                                {% if solution.user == request.user %} disabled {% endif %}" href="{% url 'solutions:vote_solution' pk=solution vote='upvote' %}">Fajne</a>
                            </div>
                        </div>
                        {% include 'comments/_commentSection.html' with comments=solution.comments solution_id=solution.id %}

                    </div>
                </div>
            {% endfor %}
            {% if not solutions %}
                <p>Nikt jeszcze nie rozwiązał tego zadania...</p>
            {% endif %}
        </div>
        <form id="commentForm" autocomplete="off" class="border-top border-2 pt-3" style="display:none;">
            {% crispy comment_form %}
        </form>
        {% endif %}
    </div>
    <!-- Modal -->
    <div class="modal fade" id="solutionHistoryModal" tabindex="-1" aria-labelledby="solutionHistoryModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="solutionHistoryModalLabel">Historia zmian</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                        <p class="placeholder-glow">
                            <span class="placeholder col-2"></span>
                        </p>
                        <p class="placeholder-glow">
                            <span class="placeholder col-5"></span>
                            <span class="placeholder col-4"></span>
                            <span class="placeholder col-4"></span>
                            <span class="placeholder col-2"></span>
                            <span class="placeholder col-4"></span>
                            <span class="placeholder col-6"></span>
                            <span class="placeholder col-5"></span>
                            <span class="placeholder col-2"></span>
                            <span class="placeholder col-3"></span>
                            <span class="placeholder col-4"></span>
                            <span class="placeholder col-5"></span>
                            <span class="placeholder col-4"></span>
                            <span class="placeholder col-2"></span>
                        </p>
                        <p class="text-end placeholder-glow">
                            <span class="placeholder col-4"></span>
                        </p>
                    <div class="history"> </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">zamknij</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script>
        var url = "{% url 'solutions:comments:create' %}";
    </script>
    <script src="{% static 'comments/comments.js' %}"></script>
    <script src="{% static 'solutions/solution_history.js' %}"></script>
    <script src="{% static 'solutions/problem-statement-overflow.js'%}"></script>
    <script src="{% static 'solutions/solutions_vote.js'%}"></script>
{% endblock %}

solutions/templates/solutions/problemSurrender.html
<div class="d-flex my-4 flex-column">
    <div id="surrender-info">
    {% if waiting_for_surrender %}
        {% include 'solutions/_surrenderTimer.html' with pk=pk surrendered_as_solved=surrendered_as_solved%}
    {% else %}
        <p>
            Rozwiązania są ukryte, dopóki nie rozwiążesz zadania lub nie poddasz się.
        </p>
        <h4>Wysyłanie rozwiązań</h4>
            <p>Gdy rozwiążesz problem podziel się swoim rozwiązaniem wysyłając je.
                Od razu po wysłaniu otrzymasz dostęp do rozwiązań innych użytkowników,
                możliwości oceniania i komentowania ich.</p>
        <h4>Jak działa poddawanie się?</h4>
        <ul>
            <li> zobaczysz rozwiązania innych użytkowników, będziesz mógł je oceniać i komentować tak samo
                jak użytkownicy którzy rozwiązali zadanie (po 10 minutach czekania)</li>
            <li> nadal będziesz mógł dodać rozwiązanie</li>
        </ul>
        <h4>Czym nie jest poddawanie się?</h4>
        <p>
            Jeśli rozwiązałeś zadanie i chcesz porównać swoje rozwiązanie z rozwiązaniami innych <b>nie używaj tej opcji!</b>
            Zamiast tego wyślij swoje rozwiązanie zadania, lub oznacz je jako rozwiązane.
        </p>
        <h4>Uwaga:</h4>
        <p>Gdy zdecydujesz się poddać zostanie uruchomione 10-cio minutowe odliczanie, po którym otrzymasz dostęp do rozwiązań.
        W tym czasie możesz zmienić decyzję (zrezygnować z poddania się). </p>
        <div class="d-flex flex-row justify-content-end">
            <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#surrenderModal" id="surrender-modal-close">
                Poddaję się
            </button>
        </div>
        </div>
    {% endif %}
</div>

<!-- Modal -->
<div class="modal fade" id="surrenderModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Kapitulacja</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <p>
              Czy na pewno chcesz się poddać? Będziesz mieć tylko 10 minut na zmienienie decyzji.
          </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="cancel-surrender-btn">Anuluj</button>
        <a type="button" class="btn align-self-end  btn-outline-danger" id="surrender-btn" href="#">Poddaję się</a>
      </div>
    </div>
  </div>
</div>

{% load static %}
<script>
    var surrender_begin_url = "{% url 'solutions:begin_surrender' pk=pk as_solved=0 %}?version=1";
    var surrender_as_solved_begin_url = "{% url 'solutions:begin_surrender' pk=pk as_solved=1 %}?version=1";
    var surrender_timer_url = "{% url 'solutions:surrender_time' pk=pk %}";
</script>
<script src="{% static 'solutions/surrender.js' %}"></script>
{% if waiting_for_surrender %}
    <script>
        show_timer();
    </script>
{% endif %}

solutions/templates/solutions/solutionEdit.html
{% extends "problembase/problem.html" %}

{% load crispy_forms_tags %}

{% block innerContent %}
    <h1 class="mb-3">Edytujesz swoje rozwiązanie do zadania "{{ name }}"</h1>
    {% crispy solution_form %}

{% endblock %}