account/urls.py
from django.urls import path
from . import views


app_name = 'account'
urlpatterns = [
    path('login/', views.login_page, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('register/', views.register_page, name="register"),
    path('<str:pk>', views.profile_page, name="profile_page"),
    path('<str:pk>/problems', views.user_problems_added_page, name="user_problems"),
    path('<str:pk>/solutions', views.user_solutions_added_page, name="user_solutions"),
    path('<str:pk>/comments', views.user_comments_added_page, name="user_comments"),
    path('<str:pk>/notifications', views.user_notifications_page, name="user_notifications"),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name="home"),
]

problembase/urls.py
from django.urls import path, include
from . import views
from .views import ProblemBaseView
app_name = 'problems'
urlpatterns = [
    path('', ProblemBaseView.as_view(template_name="problembase/problemBase.html"), name="problem_base"),
    path('<int:pk>', views.problem_page, name="statement"),
    path('<int:pk>/info', views.problem_page_info, name="info"),
    path('upload', views.upload_problem_page, name="upload_problem"),
    path('<int:pk>/edit', views.problem_edit_page, name="edit_problem"),
    path('watch/<int:pk>', views.watch_problem_page, name="watch_problem"),
    path('history/<int:pk>', views.problem_history_page, name='history'),
    path('upload_api', views.upload_problem_api, name='upload_api'),
    path('problem_statement_api/<int:pk>', views.problem_statement_api, name='problem_statement_api'),
]

problemset/urls.py
from django.urls import path, include
from . import views

app_name = 'problemset'
urlpatterns = [
    path('create/', views.problemset_create_page, name='create'),
    path('edit_basic/<int:pk>/', views.problemset_edit_basic_page, name='edit_basic'),
    path('edit/<int:pk>/', views.problemset_edit_page, name='edit'),
    path('search_problem/', views.ProblemSearchResults.as_view(template_name="problemset/_problemSearchResults.html"), name='search_problem'),
    path('editable_problem_entry/<int:pk>', views.EditableProblemEntry, name='editable_problem_entry'),
    path('save/<int:pk>', views.ProblemsetSave, name='save'),
    path('<int:pk>', views.ProblemsetView, name='problemset'),
    path('problem/<int:problemset_pk>/<int:problem_pk>', views.ProblemInProblemset, name='problem_in_problemset'),
    path('unregister_eiting_notification', views.UnregisterProblemsetEiditingNotification, name='unregister_editing_notification'),
    path('list', views.ProblemsetListView.as_view(template_name="problemset/problemsetList.html"), name="problemset_list"),
]

problemset/models.py
from django.db import models
from base.models import User
from datetime import datetime, timedelta

def content_default():
    return []

class Problemset(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=300, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.JSONField(default=content_default())
    date = models.DateTimeField(auto_now_add=True)
    featured = models.BooleanField(default=False)

    def __str__(self):
        return str(self.name)

class UserToProblemset(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    problemset = models.ForeignKey(Problemset, on_delete=models.CASCADE)
    last_visit = models.DateTimeField(null=True)
    solved_count = models.IntegerField(default=0)
    surrendered_count = models.IntegerField(default=0)
    total_count = models.IntegerField(default=None, null=True)

    def timestamp(self):
        self.last_visit = datetime.now()
        self.save()

    def is_progress_valid(self):
        return self.total_count is not None

    def invalidate_progress_cache(self):
        self.total_count = None
        self.save()


class ProblemsetDuringEditing(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    problemset = models.ForeignKey(Problemset, null=True, on_delete=models.CASCADE)

problemset/forms.py
from django.forms import ModelForm
from django import forms
from base.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Submit, Row, Column, Div, Field, HTML
from .models import Problemset

EXPLANATION = 'Zostaniesz przeniesionu do strony edycji, gdzie będziesz mógł dodać zadania do zbioru.'


class ProblemsetForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column(Field('name'), css_class="col-lg-8"),
            Field('description', rows=2),
            Div(HTML(EXPLANATION), css_class="d-flex mb-2"),
            Div(Submit('submit', 'Zapisz', css_class='d-flex'), css_class='d-flex flex-row justify-content-end'),
        )
        self.fields["name"].label = "Nazwa zbioru"
        self.fields["description"].label = "Opis (opcjonalny)"
        self.fields["description"].widget = forms.Textarea()


    class Meta:
        model = Problemset
        fields = ['name', 'description']

problemset/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.template.response import TemplateResponse
from django.views.generic.list import ListView
from django.http import HttpResponse
from django.urls import reverse
from django.utils.decorators import method_decorator

from base.models import Problem
from notifications.views import show_notifications
from .forms import ProblemsetForm
from .models import Problemset, UserToProblemset
from .utils import process_problemset_content, get_problemset_progress, get_motivation_on_progress, register_problemset_editing_notification, unregister_problemset_editing_notification, attach_problemset_progress
from problembase.utils import add_stats_to_problems, add_status_to_problems
from base.models import UserToProblem
from problembase.forms import UploadForm
import json

# Create your views here.
@show_notifications
@login_required(login_url='account:login')
def problemset_create_page(request):
    form = ProblemsetForm()

    if request.method == 'POST':
        form = ProblemsetForm(request.POST)

        if form.is_valid():
            problemset = form.save(commit=False)

            setattr(problemset, "user", request.user)
            problemset.save()

            return redirect('problemset:edit', pk=problemset.pk)

    context = {'form': form}

    return TemplateResponse(request, "problemset/problemsetCreate.html", context)

@show_notifications
@login_required(login_url='account:login')
def problemset_edit_basic_page(request, pk):
    problemset = get_object_or_404(Problemset, pk=pk)

    if request.user != problemset.user:
        raise PermissionDenied()

    form = ProblemsetForm(request.POST or None, instance=problemset)
    if form.is_valid():
        problemset = form.save(commit=False)
        problemset.save()
        return redirect('problemset:edit', pk=problemset.id)

    context = {
        'form': form,
    }
    return TemplateResponse(request, "problemset/problemsetCreate.html", context)

@show_notifications
@login_required(login_url='account:login')
def problemset_edit_page(request, pk):
    problemset = get_object_or_404(Problemset, pk=pk)
    if problemset.user != request.user:
        raise PermissionDenied()

    register_problemset_editing_notification(request.user, problemset)
    json = problemset.content
    process_problemset_content(json, request.user)
    context = {
        'problemset': problemset,
        'rows': json,
        'problem_form': UploadForm(),
    }
    return TemplateResponse(request, "problemset/problemsetEdit.html", context)


class ProblemSearchResults(ListView):
    model = Problem
    paginate_by = 15


    def get_queryset(self):
        q = self.request.GET.get('q') if self.request.GET.get('q') is not None else ''
        object_list = Problem.objects.filter(
            Q(category__name__icontains=q) |
            Q(name__icontains=q)
        ).order_by('-creation_date')
        return object_list

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        add_stats_to_problems(data['object_list'])
        add_status_to_problems(data['object_list'], self.request.user)
        return data

def EditableProblemEntry(request, pk):
    problem = get_object_or_404(Problem, pk=pk)
    context = {
        'problem': problem,
    }
    return render(request, 'problemset/_editableProblemEntry.html', context)

@login_required(login_url='account:login')
def ProblemsetSave(request, pk):
    if request.method == 'POST':
        problemset = get_object_or_404(Problemset, pk=pk)
        if problemset.user != request.user:
            raise PermissionDenied()
        problemset.content = json.loads(request.POST.get('json'))
        problemset.save()
        response_data = {}
        response_data['result'] = 'Problemset saved successfully!'
        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )

    else:
        raise PermissionDenied()

@login_required(login_url='account:login')
def ProblemsetView(request, pk):
    problemset = get_object_or_404(Problemset, pk=pk)
    utpset, _ = UserToProblemset.objects.get_or_create(user=request.user, problemset=problemset)
    utpset.timestamp()
    utpset.invalidate_progress_cache()

    unregister_problemset_editing_notification(request.user)
    content = problemset.content
    process_problemset_content(content, request.user)
    progress = get_problemset_progress(problemset, request.user)
    context = {
        'problemset': problemset,
        'progress': progress,
        'rows': content,
        'motivational_proggress_message': get_motivation_on_progress(progress['solved_amount']),
    }
    return TemplateResponse(request, "problemset/problemsetPage.html", context)

@login_required(login_url='account:login')
def ProblemInProblemset(request, problem_pk, problemset_pk):
    problem = get_object_or_404(Problem, pk=problem_pk)
    problemset = get_object_or_404(Problemset, pk=problemset_pk)
    utp, _ = UserToProblem.objects.get_or_create(problem=problem, user=request.user)
    utp.seen_in_problemset = problemset
    utp.save()
    return redirect(reverse('problems:statement', kwargs={'pk': problem_pk}))

@method_decorator(show_notifications, name='dispatch')
@method_decorator(login_required(login_url='account:login'), name='dispatch')
class ProblemsetListView(ListView):
    model = Problemset
    paginate_by = 10

    def get_queryset(self):
        q = self.request.GET.get('q') if self.request.GET.get('q') is not None else ''
        object_list = Problemset.objects.filter(
            Q(description__icontains=q) |
            Q(name__icontains=q)
        ).order_by('-date')
        if self.request.GET.get('user'):
            object_list = object_list.filter(user=self.request.GET.get('user'))
        if self.request.GET.get('featured'):
            object_list = object_list.filter(featured=self.request.GET.get('featured'))
        return object_list

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        for problemset in data['object_list']:
            attach_problemset_progress(problemset, self.request.user)
        return data

@login_required(login_url='account:logn')
def UnregisterProblemsetEiditingNotification(request):
    unregister_problemset_editing_notification(request.user)

    response_data = {
        'result': 'Unregistered!',
    }
    return HttpResponse(
        json.dumps(response_data),
        content_type="application/json"
    )

problemset/templates/problemset/_editableComment.html
<li class="ms-4 fs-6 pt-0 list-group-item list-group-item-action border-0 entry" data-type='comment' style="cursor: move;">
    <p class="text-secondary" style="display: inline;">{{ comment.name }}</p>
    <span class="edit-name" style="display: none; cursor: pointer;"><i class="px-1 bi bi-pencil-square"></i></span>
    <input class='w-75' type="text" value="{{ comment.name }}" style="display: none;">
    <span class="delete-list-item" style="display: none; cursor: pointer;"><i class="px-1 bi bi-trash"></i></span>
</li>

problemset/templates/problemset/_editableHeading.html
<li class="pb-1 list-group-item list-group-item-action border-0 entry" data-type="heading" style="cursor: move;">
    <h4 style="display: inline;">{{ heading.name }}</h4>
    <span class="hide edit-name" style="display: none; cursor: pointer;"><i class="px-1 bi bi-pencil-square"></i></span>
    <input type="text" value="{{ heading.name }}" style="display: none;">
    <span class="delete-list-item" style="display: none; cursor: pointer;"><i class="px-1 bi bi-trash"></i></span>
</li>

problemset/templates/problemset/_editableProblemEntry.html
<li class="ms-4 py-1 problem-item list-group-item list-group-item-action border-0 entry" data-type="problem" data-id="{{ problem.id }}" style="cursor: move;">
    <a class="problem-link" href="{% url 'problems:statement' pk=problem.id %}" data-problem-id="{{ problem.id }}">{{ problem.name }}</a>
    <span class="edit-name" style="display: none; cursor: pointer;"><i class="px-1 bi bi-pencil-square"></i></span>
    <input type="text" value="{{ problem.name }}" style="display: none;">
    <span class="delete-list-item" style="display: none; cursor: pointer;"><i class="px-1 bi bi-trash"></i></span>
</li>

problemset/templates/problemset/_problemSearchResults.html
<div class="search-results d-flex flex-column mt-5">
    {% if object_list %}
    <table class="table table-borderless table-hover">
        <tbody>
        {% for problem in object_list %}
            {% include 'problembase/problemDBEntry.html' with problem=problem %}
        {% endfor %}
        </tbody>
    </table>
    <div class="d-flex flex-row justify-content-center" id="search-results-navigation">
        {% include 'problembase/_pagination_nav.html' with page_obj=page_obj %}
    </div>
    {% else %}
        <p>Brak wyników.</p>
    {% endif %}
</div>

problemset/templates/problemset/_problemsetPreview.html
<div class="card" style="width: 18rem;">
  <div class="card-header">
      <a class="text-primary text-decoration-none" href="{% url 'problemset:problemset' pk=problemset_data.id %}"> {{ problemset_data.name }} -></a>
  </div>
  <ul class="list-group list-group-flush">
        {% if problemset_data.more_before %}
            <li class="list-group-item">...</li>
        {% endif %}
        {% for row in problemset_data.rows %}
            <li class="list-group-item {% if row.selected %}list-group-item-secondary{% endif %}">
            {% if row.type == "problem" %}
                <a class="text-decoration-none" href="{% url 'problemset:problem_in_problemset' problem_pk=row.id problemset_pk=problemset_data.id %}">{{ row.name }}</a>
                  <span class="d-inline">
                      {% include 'problembase/_problemStatus.html' with problem=row %}
                  </span>
            {% elif row.type == "heading" %}
                  <h6 style="display: inline;">{{ row.name }}</h6>
            {% elif row.type == "comment" %}
                  <p class="text-secondary" style="display: inline;">{{ row.name }}</p>
            {% endif %}
            </li>
          {% endfor %}
      {% if problemset_data.more_ahead %}
          <li class="list-group-item">...</li>
      {% endif %}
  </ul>
</div>

problemset/templates/problemset/_uploadProblemModal.html
<!-- Modal -->
{% load crispy_forms_tags %}
<div class="modal fade" id="problemUploadModal" tabindex="-1" aria-labelledby="problemUploadModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="problemUploadModalLabel">Utwórz nowe zadanie</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="problemUploadForm" method="post" action="{% url 'problems:upload_api' %}">
                    {%  crispy problem_form %}
                </form>
            </div>
            <div class="modal-footer">
                <div class="spinner-border spinner-border-sm" style="display: none;"></div>
            </div>
        </div>
    </div>
</div>
<style>
    .cke_dialog_ui_input_textarea textarea {z-index: 9999 !important;}
    :root {
        --ck-z-default: 100;
        --ck-z-modal: calc( var(--ck-z-default) + 999 );
    }
</style>

{% load static %}
<script>var upload_problem_url = "{% url 'problems:upload_api' %}"</script>
<script src="{% static 'problemset/upload_problem_modal.js' %}"></script>

problemset/templates/problemset/problemsetCreate.html
{% extends 'base/base.html' %}

{% load crispy_forms_tags %}
{% block content %}
    {% crispy form %}
{% endblock %}

problemset/templates/problemset/problemsetEdit.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
    <div class="d-flex flex-row">
        <div class="d-flex flex-column w-50">
            <h3 class="text-break">
                {{ problemset.name }}
                <a class="" href="{% url 'problemset:edit_basic' pk=problemset.pk %}"><i class="bi bi-pencil-square"></i></a>
            </h3>
            <p class="text-secondary text-break">{{ problemset.description }}</p>
            <ul class="h5 editable-problemset list-group list-group-flush sortable text-break" style="min-width: 0;">
                {% csrf_token %}
                {% for row in rows %}
                    {% if row.type == "problem" %}
                        {% include 'problemset/_editableProblemEntry.html' with problem=row %}
                    {% elif row.type == "heading" %}
                        {% include 'problemset/_editableHeading.html' with heading=row%}
                    {% elif row.type == "comment" %}
                        {% include 'problemset/_editableComment.html' with comment=row%}
                    {% endif %}
                {% endfor %}
                <li class="toolbar text-center list-group-item">
                    <button id="add-heading" class="btn btn-outline-primary add-heading">+Nagłówek</button>
                    <button id="add-comment" class="btn btn-outline-primary add-comment">+Komentarz</button>
                    <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#problemUploadModal">+Nowe zadanie</button>
                </li>
            </ul>
            <div class="text-end autosave-status text-secondary mt-3">Zapisano wszystkie zmiany.</div>
            <div class="text-end mt-2"><a class="btn btn-outline-primary" href="{% url 'problemset:problemset' pk=problemset.pk %}">Gotowe</a></div>
        </div>
        <div class="d-flex flex-column border-start border-4 ms-5 px-4 w-50" style="min-width: 600px;">
            <h4>Szukaj zadań</h4>
            <form id="problemset-search-problem" class="d-flex" role="search" method="GET" action="{% url 'problemset:search_problem' %}">
                <input class="w-75 form-control me-2" type="text" name="q" placeholder="Szukaj zadania..."
                       aria-label="Search">
                <div class="ms-3" id="search-placeholder" style="display: none">
                    <div class="spinner-border" role="status">
                        <span class="visually-hidden">Loading...</span>
                    </div>
                </div>
            </form>
            <div class="d-flex" id="search-results-container">
            </div>
        </div>
    </div>
    <template id="headingTemplate">
        {% include 'problemset/_editableHeading.html' %}
    </template>
    <template id="commentTemplate">
        {% include 'problemset/_editableComment.html' %}
    </template>
    <script>var editable_problem_entry_url = "{% url 'problemset:editable_problem_entry' pk=0 %}"</script>
    <script>var problemset_save_url = "{% url 'problemset:save' pk=problemset.pk %}"</script>
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <script src="{% static 'problemset/problemset_edit.js' %}"></script>
    {% include 'problemset/_uploadProblemModal.html' %}
{% endblock %}

{% block scripts %}
{% endblock %}

problemset/templates/problemset/problemsetList.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="home-container d-flex flex-row p-4 h-100 justify-content-center">
        <nav class="collapse d-lg-block sidebar collapse" style="max-width: 300px;">
            <div class="list-group list-group-flush mx-3 mt-4">
                <h3 class="">Zbiorki zadań</h3>
                <div class="list-group-item text-secondary">
                    <p>Tutaj możesz szukać, rozwiązywać i tworzyć zbiorki zadań.
                        Przerobienie sprawdzonego zestawu problemów jest o wiele lepsze od klepania losowych zadań. Jest też większa satysfakcja!</p>
                </div>
                <a style="text-decoration: none;"
                   href="{% url 'problemset:problemset_list' %}?featured=True"
                   class="list-group-item list-group-item-action py-2 ripple">
                    <span> Wyróżnione zbiorki </span>
                </a>
                <a style="text-decoration: none;"
                   href="{% url 'problemset:problemset_list' %}?user={{ request.user.id }}"
                   class="list-group-item list-group-item-action py-2 ripple">
                    <span> Moje zbiorki </span>
                </a>
                <div class="list-group-item mt-3">
                    <a class="btn btn-outline-secondary" href="{% url 'problemset:create' %}">Nowy zbiorek</a>
                </div>
            </div>
        </nav>

        <div class="d-flex" style="width: 120px"><!-- spacing between categories and problems --></div>
        <div class="d-flex list-group list-group-flush w-50">
            <form class="d-flex flex-row justify-content-center" role="search" method="GET" action="{% url 'problemset:problemset_list' %}">
                <input class="form-control m-3 mb-4 w-75" type="text" name="q" placeholder="Szukaj zbiorku..."
                       aria-label="Search">
            </form>
            {% if not object_list %}
                <p>Nie znaleźliśmy niczego ://</p>
            {% endif %}
            {% for problemset in object_list %}
            <div class="list-group-item text-break py-4">
                <a class='text-decoration-none border-0' href="{% url 'problemset:problemset' pk=problemset.id %}">
                <h3><span class="text-black">{{ problemset.name }}</span>
                    {% if problemset.featured %}<i class="bi bi-check-all" style="color: lightseagreen; cursor: default;" title="Wyróżniony zbiorek"></i>{% endif %}
                </h3>
                <p class="text-secondary">{{ problemset.description }}</p>
                </a>
                {% if problemset.progress.total != 0 %}
                    <div class="d-flex flex-row align-items-center">
                        <div class="d-flex progress mb-2 w-75" style="height: 10px;">
                            <span class="progress-bar bg-warning" title="{{ problemset.progress.solved_amount }}%" style="width: {{ problemset.progress.solved_amount }}%"></span>
                            <span class="progress-bar bg-secondary" title="{{ problemset.progress.surrendered_amount }}%" style="width: {{ problemset.progress.surrendered_amount }}%"></span>
                        </div>
                        <p class="d-flex ms-3 fs-5">{{ problemset.progress.solved }}/{{ problemset.progress.total }}</p>
                    </div>
                {% endif %}
            </div>
            {% endfor %}
            <div class="d-flex flex-row justify-content-center mt-3">
                {% include 'problembase/_pagination_nav.html' %}
            </div>
        </div>
    </div>
{% endblock %}

problemset/templates/problemset/problemsetPage.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="d-flex flex-column w-50 text-break">
        <h3> {{ problemset.name }}
            {% if problemset.featured %}<i class="bi bi-check-all" style="color: lightseagreen; cursor: default;" title="Wyróżniony zbiorek"></i>{% endif %}
            {% if request.user == problemset.user %} <a href="{% url 'problemset:edit' pk=problemset.pk %}">Edytuj</a>{% endif %}
        </h3>
        <p class="text-secondary">{{ problemset.description }}</p>
        {% if progress.total != 0 %}
        <div class="progress mb-2 w-100" style="height: 10px;">
            <span class="progress-bar bg-warning" title="{{ progress.solved_amount }}%" style="width: {{ progress.solved_amount }}%"></span>
            <span class="progress-bar bg-secondary" title="{{ progress.surrendered_amount }}%" style="width: {{ progress.surrendered_amount }}%"></span>
        </div>
        {% if progress.solved_amount > 30 %}
        <div class="d-flex flex-row justify-content-end pe-0" style="width: {{ progress.solved_amount }}%;">
            <span class="d-flex me-0 pe-0">{{ motivational_proggress_message }}<i class="me-0 pe-0 bi bi-arrow-up"></i></span>
        </div>
        {% else %}
            <div class="d-flex flex-row px-0 mx-0">
                <div class="d-flex" style="width: {{ progress.solved_amount }}%;"></div>
                <span class="d-flex mx-0 px-0"><i class="me-0 pe-0 bi bi-arrow-up"></i>{{ motivational_proggress_message }}</span>
            </div>
        {% endif %}
        {% else %}
            <p>W tym zbiorze zadań nie ma zadań :ooo</p>
        {% endif %}
        <ul class="h5 list-group list-group-flush text-break" style="min-width: 0;">
            {% for row in rows %}
                {% if row.type == "problem" %}
                    <li class="ms-4 py-1 list-group-item border-0 entry">
                        <a class="problem-link" href="{% url 'problemset:problem_in_problemset' problem_pk=row.id problemset_pk=problemset.pk %}" data-problem-id="{{ row.id }}">{{ row.name }}</a>
                        <span class="d-inline">
                            {% include 'problembase/_problemStatus.html' with problem=row %}
                        </span>
                    </li>
                {% elif row.type == "heading" %}
                    <li class="pb-1 list-group-item border-0 entry">
                        <h4 style="display: inline;">{{ row.name }}</h4>
                    </li>
                {% elif row.type == "comment" %}
                    <li class="ms-4 fs-6 pt-0 list-group-item border-0">
                        <p class="text-secondary" style="display: inline;">{{ row.name }}</p>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
        <div class="d-flex flex-row justify-content-end">
            <p class="text-secondary"> Zbiorek przygotował <a class="text-decoration-none" href="{% url 'account:profile_page' pk=problemset.user.pk %}">@{{ problemset.user }}</a>.</p>
        </div>
    </div>
{% endblock %}