account/urls.py
from django.urls import path
from . import views


app_name = 'account'
urlpatterns = [
    path('login/', views.login_page, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('register/', views.register_page, name="register"),
    path('<str:pk>', views.profile_page, name="profile_page"),
    path('<str:pk>/problems', views.user_problems_added_page, name="user_problems"),
    path('<str:pk>/solutions', views.user_solutions_added_page, name="user_solutions"),
    path('<str:pk>/comments', views.user_comments_added_page, name="user_comments"),
    path('<str:pk>/notifications', views.user_notifications_page, name="user_notifications"),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name="home"),
]

problembase/urls.py
from django.urls import path, include
from . import views
from .views import ProblemBaseView
app_name = 'problems'
urlpatterns = [
    path('', ProblemBaseView.as_view(template_name="problembase/problemBase.html"), name="problem_base"),
    path('<int:pk>', views.problem_page, name="statement"),
    path('<int:pk>/info', views.problem_page_info, name="info"),
    path('upload', views.upload_problem_page, name="upload_problem"),
    path('<int:pk>/edit', views.problem_edit_page, name="edit_problem"),
    path('watch/<int:pk>', views.watch_problem_page, name="watch_problem"),
    path('history/<int:pk>', views.problem_history_page, name='history'),
    path('upload_api', views.upload_problem_api, name='upload_api'),
    path('problem_statement_api/<int:pk>', views.problem_statement_api, name='problem_statement_api'),
]

problemset/urls.py
from django.urls import path, include
from . import views

app_name = 'problemset'
urlpatterns = [
    path('create/', views.problemset_create_page, name='create'),
    path('edit_basic/<int:pk>/', views.problemset_edit_basic_page, name='edit_basic'),
    path('edit/<int:pk>/', views.problemset_edit_page, name='edit'),
    path('search_problem/', views.ProblemSearchResults.as_view(template_name="problemset/_problemSearchResults.html"), name='search_problem'),
    path('editable_problem_entry/<int:pk>', views.EditableProblemEntry, name='editable_problem_entry'),
    path('save/<int:pk>', views.ProblemsetSave, name='save'),
    path('<int:pk>', views.ProblemsetView, name='problemset'),
    path('problem/<int:problemset_pk>/<int:problem_pk>', views.ProblemInProblemset, name='problem_in_problemset'),
    path('unregister_eiting_notification', views.UnregisterProblemsetEiditingNotification, name='unregister_editing_notification'),
    path('list', views.ProblemsetListView.as_view(template_name="problemset/problemsetList.html"), name="problemset_list"),
]

ranking/urls.py
from django.urls import path
from . import views


app_name = 'ranking'
urlpatterns = [
    path('', views.ranking_page, name="ranking"),
    path('<int:pk>', views.ranking_selected, name="ranking-selected"),
]

base/models.py
from django.db import models
from datetime import datetime, timedelta
from ckeditor.fields import RichTextField
from django.contrib.auth.models import AbstractUser


# Create your models here.


class User(AbstractUser):
    pass


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return str(self.name)


class Problem(models.Model):
    name = models.CharField(max_length=100)
    creation_date = models.DateTimeField(auto_now_add=True)
    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    problem_statement = RichTextField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    watchers = models.JSONField("Watchers", default={"watcher": "task"})
    source = models.CharField(max_length=100)
    edited = models.BooleanField(default=False)

    def problem_id(self):
        return self.id

    def problem_name(self):
        return self.name

    def display(self):
        return self.problem_statement

    def __str__(self):
        return str(self.name)

class Solution(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    upvote_counter = models.IntegerField(default=0)
    creation_date = models.DateTimeField(auto_now_add=True)
    content = RichTextField(blank=True, null=True)
    edited = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

    def problem_id(self):
        return self.problem.id

    def problem_name(self):
        return self.problem.name

    def display(self):
        return self.content

class UserToProblem(models.Model):
    # CASCADE := when deleted, child will also be deleted.
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    surrendered = models.BooleanField(default=False)
    began_surrendering = models.BooleanField(default=False)
    surrender_end_time = models.DateTimeField(null=True)
    surrendering_as_solved = models.BooleanField(default=False)
    is_watching = models.BooleanField(default=False)
    last_visit = models.DateTimeField(null=True)
    seen_in_problemset = models.ForeignKey("problemset.Problemset", null=True, on_delete=models.SET_NULL)

    def timestamp(self):
        self.last_visit = datetime.now()
        self.save()

    def start_surrendering(self):
        self.surrender_end_time = datetime.now() + timedelta(minutes=10)
        self.began_surrendering = True;
        self.save();

    class Meta:
       unique_together = ['problem', 'user']

    def __str__(self):
        return str(self.user) + " " + str(self.problem)


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    solution = models.ForeignKey(Solution, on_delete=models.CASCADE)
    content = models.CharField(max_length=300, default="")
    creation_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    upvote_counter = models.IntegerField(default=0)

    def __str__(self):
        return str(self.content)

    def problem_id(self):
        return self.solution.problem.id

    def problem_name(self):
        return self.solution.problem.name

    def display(self):
        return self.content


class SolutionVote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    solution = models.ForeignKey(Solution, on_delete=models.CASCADE)
    value = models.IntegerField(default=0)

    def __str__(self):
        return str(self.user) + " " + str(self.solution) + " " + str(self.value)


class CommentVote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    value = models.IntegerField(default=0)

    def __str__(self):
        return str(self.user) + " " + str(self.comment) + " " + str(self.value)

base/views.py
from django.shortcuts import render

# Create your views here.
def page_404(request, exception):
    return render(request, 'base/404.html', status=404)

def page_403(request, exception):
    return render(request, 'base/403.html', status=403)

base/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Solak {% endblock %}</title>

    <!-- Bootstrap -->
    <link rel=stylesheet type='text/css' href="{% static 'base/bootstrap.min.css' %}">

    <!-- stylesheet -->

    <!-- Bootstrap Font Icon CSS -->
    <link rel="stylesheet" href=
"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" />

    <!-- Mathjax -->
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>

    <!-- favicon -->
    <link rel="icon" type="image/png" href="{% static 'base/favicon.png' %}">
    <script>
        var csrf_token1 = '{{ csrf_token }}';
    </script>
    <script>var problem_statement_api_url = "{% url 'problems:problem_statement_api' pk=0 %}"</script>
    <script src="{% static 'problembase/problem_preview.js' %}"></script>
    {% block scripts %}
    {% endblock %}
</head>
<body class="d-flex flex-column min-vh-100 h-100">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>

    {% include 'base/navbar.html' %}

    <div id="content", name="content", class="mx-5 mt-5 d-flex justify-content-center" style="margin-bottom: 100px;">

    {% block content %}
    {% endblock %}
    </div>
    {% block footer %}
        {% include "base/footer.html" %}
    {% endblock %}
</body>

<style>
.prevent-select {
  -webkit-user-select: none; /* Safari */
  -ms-user-select: none; /* IE 10 and IE 11 */
  user-select: none; /* Standard syntax */
}

.home-container {
    display: grid;
    grid-template-columns: 1fr 6fr;
}
.problem-link {
 text-decoration: none;
}
.fade-overflow:after {
    content: '';
    display: block;
    position: absolute;
    right: 0;
    bottom: 0;
    left: 0;
    height: 2lh; /* 100% - (line-height × 3) */
    background: linear-gradient(rgba(255, 255, 255, 0), #ffffff); /* line-height */
}
</style>
</html>

base/templates/base/footer.html
 <footer class="bg-light text-center text-lg-start mt-auto footer w-100">
<div class="text-center p-3">
    © 2023 Copyright:
    <a class="text-dark" href="">Mateusz & Mateusz</a>
  </div>
 </footer>

 <style>
     .footer {
         position: fixed;
         bottom: 0;
     }
 </style>

base/templates/base/nakedBase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Solak {% endblock %}</title>
    <!-- Bootstrap -->
    <link rel=stylesheet type='text/css' href="{% static 'base/bootstrap.min.css' %}">
    <!-- favicon -->
    <link rel="icon" type="image/png" href="{% static 'base/favicon.png' %}">
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>

    <div id="content", name="content", class="mx-5 mt-5 d-flex justify-content-center align-items-center" style="margin-bottom: 100px;">

        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

base/templates/base/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:home' %}"><img src="{% static 'base/logo.png' %}" alt="" height="32px"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Strona główna</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'problems:problem_base' %}">Zadania</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'problemset:problemset_list' %}">Zbiorki zadań <span class="badge bg-danger rounded-pill">New</span> </a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Kategorie
                    </a>
                    <ul class="dropdown-menu">
                        {% for category in categories %}
                            <li><a class="dropdown-item" href="{% url 'problems:problem_base' %}?q={{ category }}">{{ category }}</a></li>
                        {% endfor %}
                    </ul>
                </li>

                <!--
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ranking:ranking' %}">Ranking</a>
                </li>
                 -->
                {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            @{{ request.user.username }}
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'account:profile_page' request.user.id %}">Mój
                                profil</a></li>
                            <li><a class="dropdown-item" href="{% url 'account:logout' %}">Wyloguj</a></li>
                        </ul>
                    </li>
                    {% include 'notifications/notification_bell.html' %}
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:login' %}">Zaloguj</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <form class="d-flex" role="search" method="GET" action="{% url 'problems:problem_base' %}">

                        <input class="form-control me-2" type="text" name="q" placeholder="Szukaj zadania..."
                               aria-label="Search">
                    </form>
                </li>
            </ul>
        </div>
    </div>
</nav>